// ======================================
// GameForge AI
// executor.js
// AI Task Executor
// ======================================


import {
    executeTool
} from "./tools.js";



// --------------------------------------
// 実行設定
// --------------------------------------

const ExecutorConfig = {

    maxActions:20

};



// --------------------------------------
// タスク解析
// --------------------------------------

function analyzeTask(task){


    const text =
        task.toLowerCase();



    if(
        text.includes("作成") ||
        text.includes("追加")
    ){

        return "create";

    }



    if(
        text.includes("修正") ||
        text.includes("更新")
    ){

        return "update";

    }



    if(
        text.includes("確認") ||
        text.includes("検索")
    ){

        return "search";

    }



    return "none";


}



// --------------------------------------
// Tool選択
// --------------------------------------

function selectTool(action){


    const tools = {


        create:
        "createFile",


        update:
        "updateFileContent",


        search:
        "searchProject"


    };


    return tools[action] || null;


}



// --------------------------------------
// 1タスク実行
// --------------------------------------

async function executeTask(task){


    const action =
        analyzeTask(task);



    const tool =
        selectTool(action);



    if(!tool){


        return {


            success:false,


            task,


            message:
            "実行可能なToolなし"


        };


    }



    let args={};



    switch(tool){


        case "searchProject":


            args={

                query:task

            };


            break;



        case "createFile":


            args={

                path:
                "generated/newFile.js",


                content:
                "// Generated by GameForge AI"


            };


            break;



        case "updateFileContent":


            args={

                path:
                "generated/file.js",


                content:
                "// Updated by GameForge AI"


            };


            break;


    }



    const result =
        executeTool(

            tool,

            args

        );



    return {


        success:true,


        task,


        tool,


        result


    };


}



// --------------------------------------
// Plan実行
// --------------------------------------

export async function executePlan(plan){


    const results=[];



    let count=0;



    for(
        const task of plan.tasks
    ){


        if(
            count >= ExecutorConfig.maxActions
        ){

            break;

        }



        const result =
            await executeTask(task);



        results.push(result);



        count++;


    }



    return {


        planId:
        plan.id,


        actions:
        results.length,


        results



    };


}



// --------------------------------------
// 結果整形
// --------------------------------------

export function formatExecution(result){


    let text =
`
## 実行結果

実行数:
${result.actions}

`;



    result.results.forEach(

        r=>{


            text +=
`
${r.task}

Tool:
${r.tool || "なし"}

結果:
${JSON.stringify(r.result)}

`;

        }

    );



    return text;


}
